name: Update GitHub Metrics

on:
  # Schedule updates (every 4 hours)
  schedule:
    - cron: "5 0/4 * * *" # Runs at 5 minutes past every 4th hour
  # Allow manual triggering and run on pushes to main/master branches
  workflow_dispatch:
  push:
    branches:
      - "master"
      - "main"

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Use the Metrics action
      - name: Generate GitHub Metrics
        uses: lowlighter/metrics@latest
        with:
          # GitHub token for authentication
          token: ${{ secrets.METRICS_TOKEN }}

          # User Configuration
          user: JS-JeevaSaravanan
          template: classic
          base: ""
          config_timezone: Asia/Kolkata
          filename: assets/gen/metrics.svg

          # Plugin Configuration
          plugin_languages: yes
          plugin_languages_analysis_timeout: 15
          plugin_languages_sections: most-used, recently-used
          plugin_languages_categories: markup, programming
          plugin_languages_colors: github
          plugin_languages_ignored: css, jupyter notebook, html
          plugin_languages_limit: 8
          plugin_languages_recent_categories: markup, programming
          plugin_languages_recent_days: 14
          plugin_languages_recent_load: 1000
          plugin_languages_threshold: 0%
          plugin_languages_indepth: yes
          plugin_languages_details: lines, percentage
          plugin_languages_other: no

          # Commit Authoring Configuration
          commits_authoring: Jeeva Saravanan, JS-JeevaSaravanan, jeevatamil2000@users.noreply.github.com
